server:
  extraFlags:
    - web.enable-remote-write-receiver
serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090
