mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib

service:
  # Enable the creation of a Service.
  # By default, it's enabled on mode != daemonset.
  # However, to enable it on mode = daemonset, its creation must be explicitly enabled
  enabled: true
  type: ClusterIP

presets: {}

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318

    prometheus:
      config:
        scrape_configs:
        - job_name: kubernetes-nodes-cadvisor
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
          - role: node
          metrics_path: /metrics/cadvisor
          relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - source_labels:
            - __metrics_path__
            target_label: metrics_path
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
  processors:
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25

    batch: {}

  exporters:
    debug:
      verbosity: detailed
    prometheus_remote_write:
      endpoint: "http://prometheus-server.monitoring.svc.cluster.local/api/v1/write"
      resource_to_telemetry_conversion:
        enabled: true
        
    otlp/jaeger:
      endpoint: jaeger.otel-demo.svc.cluster.local:4317
      tls:
        insecure: true

  service:
    pipelines:
      metrics:
        receivers:
          - prometheus
          - otlp
        processors:
          - memory_limiter
          - batch
        exporters:
          - debug
          - prometheus_remote_write

      traces:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - batch
        exporters:
          - debug
          - otlp/jaeger

      logs:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - batch
        exporters:
          - debug
extraEnvs:
  - name: K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName

clusterRole:
  create: true
  rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
      - ingresses
      - configmaps
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - ingresses/status
      - ingresses
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
  - verbs:
      - get
    nonResourceURLs:
      - /metrics
