mode: daemonset

image:
  repository: otel/opentelemetry-collector-k8s

presets: {}

config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

  processors:
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25

    batch: {}

  exporters:
    debug:
      verbosity: detailed

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [debug]

      metrics:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [debug]

      logs:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [debug]
